### ISSUE TITLE
LUA scripts cannot be used with default settings

### ISSUE THREAD

**Issue by nhtctn** [vcprocles/aegisub-procles-snap#4] opened 2022-09-15 19:48 UTC
Hi.

The LUA script support on Aegisub gives us ability to add / write extentions for application. A friend of mine writes excellent LUA's for diverse purpose. In windows we add LUA files to "program files" of application. That's how they are installed. An example:
`C:/Program Files (x86)/Aegisub/automation/autoload/mag.check_lines.lua`

I searched Aegisub folders on snap and home directories. Smillar folders are here:
`/snap/aegisub-procles/11/usr/local/share/aegisub/automation/autoload`
There is some default LUAs in here, but application won't see them. Normally they should be in "Automation" tab on the menu. It is empty instead.

There is "Automation" option menu for LUA scripts on Preferences. We can choose LUA folders. I create folders under `/home/nihat/snap/aegisub-procles/11/.aegisub/`, place scripts in it and write their paths to options. It worked fine. Now i can use LUA scripts.
![Ekran görüntüsü 2022-09-15 22-43-50](https://user-images.githubusercontent.com/19926602/190494947-35988136-cdb8-440f-aa98-793eef28531f.png)
![Ekran görüntüsü 2022-09-15 22-40-37](https://user-images.githubusercontent.com/19926602/190494346-2980388b-275d-47d4-a8ee-bafc4cc884e0.png)

I recomment to edit source codes to create folders under /home (we can't change /snap directiory) and change default paths to theirs. So that user can be use LUAs.

**Comment by vcprocles** [comment] 2022-09-15 22:01
1. Snap has no access to hidden folders and files in user home folder through the `home` interface. Thus, the only way to make this change is to create a non-hidden folder somewhere. Not only this may be irritating for some, this also breaks the default and expected behavior even more than snap already does.

2. As for the path issues. I tried to look into the app code, which I did not actually touch at all before. 
I have almost no idea how big C++ projects work, and I can't do anything about this.
Wontfix for now, maybe someone smarter will drop by later and volunteer to help.

**Comment by nhtctn** [comment] 2022-09-16 12:36
1. I choose that hidden path just randomly. Like you say, an unhidden path would be better. By the way `/home/nihat/snap/aegisub-procles` path was already exist and unhidden. Snap already had created some folders under home directory. Is adding some LUA folders under that a really big problem?

2. Thank you nevertheless. This was not a big issue and won't stop me to use Aegisub in linux anyway. Then you may consider adding some instructions or refer this issue to let people know how they can use LUAs.

**Comment by vcprocles** [comment] 2022-09-17 07:18
> 2\. Then you may consider adding some instructions or refer this issue to let people know how they can use LUAs.

Thanks for the suggestion, I'll update the description on the store page with some info about issues like fonts on some distros and paths to LUAs.

**Comment by vcprocles** [comment] 2022-09-17 12:22
Default lua location was fixed as of -snap2.99.2, currently in `edge` channel. You can update to it (`sudo snap refresh --edge aegisub-procles`) and confirm if it works or not.
But this is only for default scripts. You can't add new ones to their location because snaps work as a singular read-only mountable file.
User luas will require to copy the default scripts into another location and adding new ones there. I might later add a script to do that automatically, which the user will be able to call with a command like `aegisub-procles.prepare-for-user-automations` or something like that.

P.S. this fix might've fixed some other hidden issue too

**Comment by vcprocles** [comment] 2022-09-19 20:20
Added a script aegisub-procles.move-script which you can use to create a location for your scripts which will have all the default ones. Now closing the issue and preparing to push this stuff in release.

**Closed as completed by vcprocles** 2022-09-19 20:20 UTC

**Comment by nhtctn** [comment] 2022-09-19 21:27
After reinstall, checked the defaults ones and they are installed indeed. Thank you very much again.

But the usage of the move script isn't clear for me. Should i download the file and click it? Or should i write something to terminal? (I tried the second one but no luck with poor linux knowledge lol.)

**Comment by vcprocles** [comment] 2022-09-19 22:00
1. Check updates (`sudo snap refresh`)
2. Run `aegisub-procles.move-scripts`. You can use the Tab key to autocomplete.
It creates a folder in `~/snap/aegisub-procles/...` with all the default scripts in there. 
3. You then need to change the settings in the app to make them point at that location (the script tells you where exactly it put the luas)

And now you have a writable directory with all the default scripts where you can add your own.

**Comment by nhtctn** [comment] 2022-09-22 22:26
Actually i tried same thing before but it didn't work. Maybe i make a typo. Know it creates the folder. Thank you very much.

A minor issue is in Elementary OS the path on terminal is different from the path of created folder.
https://i.imgur.com/vddY5NW.png

**Comment by vcprocles** [comment] 2022-09-25 12:15
> A minor issue is in Elementary OS the path on terminal is different from the path of created folder. 

My bad, fixed in 4fd8cb5, will be pushed to everyone in a few hours
