### ISSUE TITLE
Fonts broken on non-Ubuntu distros

### ISSUE THREAD

**Issue by nhtctn** [vcprocles/aegisub-procles-snap#3] opened 2022-09-13 20:59 UTC
Hi. Me again.

OS: Linux Mint 21 Cinnamon 5.4.12

I have a lot of fonts to use. I searched how i can install them manually because installing one by one would be unpractical. According this answers:
https://askubuntu.com/questions/191778/how-to-install-many-font-files-quickly-and-easily
and here:
https://wiki.ubuntu.com/Fonts
`~/.local/share/fonts`
`~/.fonts`
Placing fonts these folders in home directiory and refresh font cache with `fc-cache -f -v` should be fine. I do these, libreoffice or video players find fonts normally. For players there is no font issue for ass subtitles.

But Aegisub don't have these fonts. I tried to refreash font cache and restart the system.

I think there is a bug about how aegisub get font list.

**Comment by vcprocles** [comment] 2022-09-14 21:39
Hello again. I did test font importing on Ubuntu 20.04 when making this snap, and it seemed to work. `fc-cache -f -v` actually does nothing for Snap packages, because they usually ship their own fontconfig, separate from the main system. I'm now setting up Mint 21 virtual machine and will look into your issues on this OS (both this issue and previous one)

**Comment by vcprocles** [comment] 2022-09-14 23:22
Update: It does seem to be a problem on my end.
On Mint 21:
1. Other snaps (gnome-font-viewer) recognize fonts installed per-user
2. Aegisub built separately but not packaged or contained by Snap recognizes fonts too.
I will now re-check in vanilla Ubuntu and look what I can do.

**Comment by vcprocles** [comment] 2022-09-14 23:49
**Works** as intended on Lubuntu 22.04 live ISO
Very weird. I now have no idea.

**Comment by nhtctn** [comment] 2022-09-15 02:20
I am trying **elementary OS 6.1** now. There is no issue with other thing, with inactive save button. Maybe that was because of i am begginer on Linux.

But user fonts won't recognized here either.

**Comment by vcprocles** [comment] 2022-09-17 10:23
Did some more digging on another distro. There is access to `~/.local/share/fonts/` and `~/.fonts/` from the confinement, but running `fc-cache -f -v` manually inside of it ignores `~/.local/share/fonts/`. It does check `~/snap/aegisub-procles/11/.local/share/fonts` and `~/.fonts`, apparently.
fonts.conf for this snap is missing one of the paths for some reason.


UPD. it just now randomly added the correct path and it just consistently works. I think i found the way to fix this.
UPD2. try removing ~/snap/aegisub-procles/current/.config/fontconfig/fonts.conf and restarting the app. I think this file generates incorrectly on first startup.
UPD3. fonts now just work on a fresh install of Mint. I don't even know what I did

**Comment by vcprocles** [comment] 2022-09-19 20:03
seems to be fixed now

**Closed as completed by vcprocles** 2022-09-19 20:03 UTC

**Comment by nhtctn** [comment] 2022-09-19 21:16
Sorry for i am late. I didn't use linux for a while. I reinstall the app and all fonts are visible now. Thank you very much!
